[tool.poetry]
name = "base"
version = "0.1.0"
description = ""
authors = ["sickerti"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
